### PR TITLE
Code style + Gravatar

### PR DESCRIPTION
**Pull request by joelkuiper**
The gravatar seems broken, but I can't figure out why ... it's the exact same code as in addis-core

### CODE REVIEW

**Comment by gertvv** [comment]
We used to use a different version of the Google API. The username might not be an e-mail address in this case?

**Comment by joelkuiper** [comment]
Ah yes, it’s some sort of ID in this case. Do you know where to change this?

**Comment by joelkuiper** [comment]
@gertvv :coffee:

**Comment by gertvv** [comment]
What happens for users who signed up before we added the e-mail field?

**Comment by joelkuiper** [comment]
They will see the default empty Gravatar (assuming you run the SQL migrations first, otherwise it will crash).

**Comment by joelkuiper** [comment]
Yeah, that last bit wasn't true. I made an assumption about the RowMapper which doesn't hold. Fix in new PR

**Pull request merged**
